// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  asset_showcase: dynamic(() => import("./AssetShowcase")),
  cta_section: dynamic(() => import("./CtaSection")),
  faq: dynamic(() => import("./Faq")),
  features: dynamic(() => import("./Features")),
  heading_hero: dynamic(() => import("./HeadingHero")),
  hero: dynamic(() => import("./Hero")),
  hove_card: dynamic(() => import("./HoveCard")),
  rich_text: dynamic(() => import("./RichText")),
  stand_out: dynamic(() => import("./StandOut")),
};
