// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  asset_showcase: dynamic(() => import("./AssetShowcase")),
  features: dynamic(() => import("./Features")),
  hero: dynamic(() => import("./Hero")),
};
