// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  asset_showcase: dynamic(() => import("./AssetShowcase")),
  blog: dynamic(() => import("./Blog")),
  cta_section: dynamic(() => import("./CtaSection")),
  faq: dynamic(() => import("./Faq")),
  features: dynamic(() => import("./Features")),
  heading_hero: dynamic(() => import("./HeadingHero")),
  hero: dynamic(() => import("./Hero")),
  hove_card: dynamic(() => import("./HoveCard")),
  how_it_works: dynamic(() => import("./HowItWorks")),
  our_story: dynamic(() => import("./OurStory")),
  page_cta: dynamic(() => import("./PageCta")),
  process_time_line: dynamic(() => import("./ProcessTimeLine")),
  rich_text: dynamic(() => import("./RichText")),
  stand_out: dynamic(() => import("./StandOut")),
  sticky_scroll: dynamic(() => import("./StickyScroll")),
  team: dynamic(() => import("./Team")),
};
